name: Test pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test :
    name: Run tests
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true    

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose build
    - name: Run Test
      run: docker-compose run test
    - name: Remove images
      if: ${{ always() }}
      run: docker-compose down